# .github/workflows/tests.yml
name: Run Tests

# Run on pushes and pull requests targeting the main branches
on:
  push:
    branches: [ main, develop ] # Adjust branch names if needed
  pull_request:
    branches: [ main, develop ]

jobs:
  run_tests:
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    strategy:
      # Run tests on multiple Python versions for compatibility checks
      matrix:
        python-version: ['3.9', '3.10', '3.11'] # Match versions in pyproject.toml classifiers

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4 # Use a recent version

      # 2. Set up the specific Python version for this job matrix entry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest

      # 4. Run tests using pytest
      - name: Run tests with pytest
        run: |
          pytest -v
